import Foundation

extension English {
    static let house: [String: String] = [
        // Nhóm, danh sách nhóm
        "Nhóm chung": "Groups",
        "Các nhóm": "Groups",
        "Nhóm mới": "New group",
        "Đóng": "Close",
        "Tạo nhóm mới": "Create new group",
        "Đã lưu trữ": "Archived",
        "%d người": "%d people",
        "%d người · %d khoản chung": "%d people · %d shared expenses",
        "Mở nhóm": "Open group",
        "Mời thành viên": "Invite members",
        "Người trong nhóm": "People in group",
        "Bỏ lưu trữ": "Unarchive",
        "Lưu trữ": "Archive",
        "Ẩn khỏi danh sách, chỉ trên máy này": "Hide from the list, on this device only",
        "Được nhận": "You get",
        "Còn phải trả": "You owe",
        "Đã cân bằng": "Settled up",

        // Trạng thái tải
        "Chưa đăng nhập iCloud": "Not signed in to iCloud",
        "Nhóm chung lưu trên iCloud. Đăng nhập iCloud trong Cài đặt của iPhone rồi mở lại.": "Groups are stored in iCloud. Sign in to iCloud in your iPhone's Settings, then open this again.",
        "Chưa tải được nhóm": "Couldn't load groups",
        "Thử lại": "Try again",

        // Tạo nhóm
        "Sổ chi tiêu chung": "Shared expense book",
        "Cho nhà chung, phòng trọ, chuyến đi… Ai ứng tiền thì ghi vào đây, Pay tính ai chuyển cho ai bao nhiêu, ít lần chuyển nhất.": "For your home, roommates, trips… Whoever pays adds it here, and Pay works out who pays whom and how much, in the fewest transfers.",
        "Tên nhóm, ví dụ: Nhà mình, Đi Đà Lạt": "Group name, e.g. Home, Đà Lạt trip",
        "Tên của bạn": "Your name",
        "Tạo nhóm": "Create group",
        "Tạo xong, mời mọi người qua Tin nhắn hoặc Zalo. Người được mời cần cài Pay và đăng nhập iCloud. Muốn vào nhóm người khác đã tạo thì bấm vào lời mời họ gửi.": "Once created, invite people via Messages or Zalo. Invitees need Pay installed and to be signed in to iCloud. To join someone else's group, tap the invite they sent you.",

        // Bạn là ai
        "Bạn là ai trong nhóm?": "Who are you in this group?",
        "Chỉ để biết phần nào là của bạn trên máy này.": "Just so this device knows which share is yours.",
        "Thêm tôi vào nhóm": "Add me to the group",

        // Thêm người, rời nhóm
        "Thêm người vào nhóm": "Add person to group",
        "Tên": "Name",
        "Huỷ": "Cancel",
        "Thêm": "Add",
        "Thêm người": "Add person",
        "Thêm được cả người không dùng Pay; bạn ghi giúp phần của họ.": "You can add people who don't use Pay; you record their share for them.",
        "Xoá nhóm cho cả nhà?": "Delete group for everyone?",
        "Rời nhóm?": "Leave group?",
        "Xoá nhóm": "Delete group",
        "Rời nhóm": "Leave group",
        "Mọi người trong nhóm sẽ mất sổ chung này. Không hoàn tác được.": "Everyone in the group will lose this shared book. This can't be undone.",
        "Sổ chung vẫn còn ở người tạo nhóm, họ mời lại được.": "The shared book stays with the group's creator, who can invite you again.",
        "Không mở được lời mời": "Couldn't open invite",
        "Mời": "Invite",

        // Trong nhóm
        "Thêm khoản chung": "Add shared expense",
        "Thông báo": "Notifications",
        "Thông báo, %d việc cần xác nhận": "Notifications, %d to confirm",
        "Thêm tài khoản nhận tiền": "Add your bank account",
        "Mọi người bấm Trả ngay là app ngân hàng điền sẵn cho bạn.": "When others tap Pay now, their bank app fills in your details.",
        "Ai chuyển cho ai": "Who pays whom",
        "%d lần": "%d transfers",
        "Mọi người đã cân bằng, không ai nợ ai.": "Everyone's settled up. Nobody owes anything.",
        "Thành viên": "Members",
        "Khoản chung": "Shared expenses",
        "Cả nhà còn nợ bạn": "The group owes you",
        "Bạn còn phải trả": "You still owe",
        "Bạn đã cân bằng": "You're settled up",
        "Bạn": "You",
        "bạn": "you",
        "Bạn trả %@": "You pay %@",
        "%@ trả bạn": "%@ pays you",
        "%@ trả %@": "%@ pays %@",
        "Trả ngay": "Pay now",
        "Đã nhận": "Received",
        "Đã chuyển": "Sent",
        "Đã có tài khoản nhận tiền": "Bank account added",
        "Chưa có tài khoản nhận tiền": "No bank account yet",
        "Trả qua app ngân hàng": "Pay with bank app",
        "Đã chuyển bằng cách khác": "Paid another way",
        "Tiền mặt, ví điện tử…": "Cash, e-wallet…",
        "Chưa có khoản chung nào. Bấm Thêm khoản chung khi bạn ứng tiền cho cả nhà.": "No shared expenses yet. Tap Add shared expense when you pay for the group.",
        "%@ ứng · chia %d người · %@": "%@ paid · split %d ways · %@",
        "bạn %@": "you %@",
        "Xoá khoản này": "Delete this expense",
        "Cả nhóm sẽ không thấy khoản này nữa": "The whole group will no longer see it",
        "Chờ xác nhận": "Awaiting confirmation",
        "Chưa nhận được": "Not received",
        "Đã xác nhận": "Confirmed",
        "%@ chuyển %@": "%@ paid %@",
        "Xoá lần trả này": "Delete this payment",
        "Số nợ sẽ tính lại như chưa trả": "Balances will be recalculated as if unpaid",
        "Hôm nay": "Today",
        "Hôm qua": "Yesterday",

        // Xác nhận chuyển
        "Xác nhận đã chuyển?": "Confirm transfer?",
        "Đã chuyển %@đ": "Sent %@đ",
        "Chưa chuyển": "Not yet",
        "Đã nhận %@đ": "Received %@đ",
        "%@ sẽ nhận thông báo để xác nhận đã nhận tiền.": "%@ will be notified to confirm they received it.",
        "Ghi nhận bạn đã nhận tiền từ %@.": "Records that you received money from %@.",

        // Cần xác nhận, thông báo
        "Cần xác nhận": "To confirm",
        "%@ báo đã chuyển cho bạn": "%@ says they paid you",
        "%@ chưa nhận được": "%@ hasn't received it",
        "Chờ %@ xác nhận": "Waiting for %@ to confirm",
        "Kiểm tra lại giao dịch trong app ngân hàng. Nếu chưa chuyển được thì chuyển lại.": "Check the transaction in your bank app. If it didn't go through, send it again.",
        "Bỏ": "Dismiss",
        "Chuyển lại": "Send again",
        "Đang tắt thông báo": "Notifications are off",
        "Bật để biết ngay khi có người báo đã chuyển tiền.": "Turn them on to know right away when someone says they've paid you.",
        "Bật": "Turn on",
        "Gần đây": "Recent",
        "Chưa có gì mới.": "Nothing new yet.",
        "Xong": "Done",
        "%@ thêm %@ %@đ": "%@ added %@ %@đ",
        "một khoản": "an expense",
        ", phần bạn %@đ": ", your share %@đ",
        "Đã báo chuyển %@đ cho %@, chờ xác nhận": "You sent %@đ to %@, awaiting confirmation",
        "%@ chưa nhận được %@đ bạn chuyển": "%@ hasn't received the %@đ you sent",
        "%@ đã nhận %@đ của bạn": "%@ received your %@đ",
        "%@ báo đã chuyển cho bạn %@đ": "%@ says they sent you %@đ",
        "Bạn báo chưa nhận được %@đ từ %@": "You reported not receiving %@đ from %@",
        "Bạn đã nhận %@đ từ %@": "You received %@đ from %@",

        // Thông báo đẩy / trên máy (House.swift)
        "%@ báo đã chuyển %@đ": "%@ says they sent %@đ",
        "Kiểm tra tài khoản rồi xác nhận đã nhận.": "Check your account, then confirm you received it.",
        "%@ chưa nhận được %@đ": "%@ hasn't received %@đ",
        "Kiểm tra lại giao dịch trong app ngân hàng hoặc chuyển lại.": "Check the transaction in your bank app, or send it again.",
        "%@ đã nhận %@đ": "%@ received %@đ",
        "Khoản trả đã được xác nhận.": "Your payment was confirmed.",
        "Người đã xoá": "Removed member",

        // Lỗi
        "Không có mạng. Thử lại khi có mạng.": "No internet connection. Try again when you're online.",
        "Máy chưa đăng nhập iCloud.": "This device isn't signed in to iCloud.",
        "iCloud đã đầy dung lượng.": "Your iCloud storage is full.",
        "Bạn không có quyền sửa nhóm này.": "You don't have permission to edit this group.",

        // Sửa thành viên
        "Chọn ảnh": "Choose photo",
        "Đổi ảnh": "Change photo",
        "Bỏ ảnh": "Remove photo",
        "Ngân hàng": "Bank",
        "Chưa chọn": "None",
        "Số tài khoản": "Account number",
        "Tài khoản nhận tiền": "Bank account for receiving",
        "Ai nợ người này bấm Trả ngay là mở app ngân hàng với sẵn số tài khoản, số tiền, nội dung.": "Anyone who owes this person can tap Pay now to open their bank app with the account number, amount and message filled in.",
        "Lưu": "Save",

        // Thêm khoản chung
        "Số tiền": "Amount",
        "Ghi chú, ví dụ: đi chợ": "Note, e.g. groceries",
        "Ai ứng tiền": "Paid by",
        "Chia đều cho": "Split equally between",
        "Bỏ chọn": "Deselect all",
        "Cả nhà": "Everyone",
        "Ghi %@đ vào chi tiêu của tôi": "Add %@đ to my spending",
        "Thống kê và ngân sách chỉ tính phần của bạn.": "Stats and budgets count only your share.",
        "Nhà chung": "Shared",

        // Dữ liệu mẫu (bản Debug)
        "Nhà mình": "Home",
        "Đi Đà Lạt": "Đà Lạt trip",
        "Đi chợ cuối tuần": "Weekend groceries",
        "Tiền điện tháng 9": "September electricity",
        "Lẩu tối thứ 6": "Friday hotpot",
        "Homestay 2 đêm": "Homestay, 2 nights",
        "Lẩu gà lá é": "Chicken hotpot",
    ]
}
